<?php
/**
 * Copyright © Dazoot Software S.R.L. rights reserved.
 * See LICENSE.txt for license details.
 *
 * @website https://www.newsman.ro/
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Dazoot\Newsmanmarketing\ViewModel\Marketing $viewModel */
$viewModel = $block->getViewModel();
if (!$viewModel->isActive()) {
    return '';
}

$pageViewScript = <<<EOT
if (typeof _nzm !== 'undefined') {
    _nzm.run('send', 'pageview');
}
EOT;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $pageViewScript, false) ?>
