<?php
/**
 * Copyright © Dazoot Software S.R.L. rights reserved.
 * See LICENSE.txt for license details.
 *
 * @website https://www.newsman.ro/
 */

/** @var \Dazoot\Newsmanmarketing\Block\EnhancedEcommerce $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var \Dazoot\Newsmanmarketing\ViewModel\Tracking $viewModel */
$viewModel = $block->getViewModel();
if (!$viewModel->isActive()) {
    return '';
}

$scriptJs = $viewModel->getScriptJs();
if (empty($scriptJs) || stripos($scriptJs, '<script') === false) {
    return '';
}

$nzmConfigJs = "_nzm_config['disable_datalayer'] = 1;";
$nzmConfigJs .= $viewModel->getNewsmanConfigJs();
?>
<?php if (!empty($nzmConfigJs)): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag(
        'script',
        [],
        "var _nzm_config = _nzm_config || [];" . $nzmConfigJs,
        false
    ); ?>
<?php endif; ?>
<?= /* @noEscape */ $scriptJs; ?>
<?php
$anonymizeIpScript = '';
if ($viewModel->getAnynymizeIp()) {
    $anonymizeIpScript = "_nzm.run('set', 'anonymizeIp', true);";
}
$noTrackingScript = $block->getChildHtml('newsman.remarketing.no-track-js');
$currencyCode = $viewModel->getCurrencyCode();

$scriptString = <<<EOT
    {$noTrackingScript}
    {$anonymizeIpScript}
    _nzm.run( 'set', 'currencyCode', '{$escaper->escapeJsQuote($currencyCode)}' );
EOT;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
