<?php
/**
 * Copyright © Dazoot Software S.R.L. rights reserved.
 * See LICENSE.txt for license details.
 *
 * @website https://www.newsman.ro/
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Dazoot\Newsmanmarketing\ViewModel\Checkout\Purchase $viewModel */
$viewModel = $block->getViewModel();
if (!$viewModel->isActive()) {
    return '';
}

$serializer = $viewModel->getSerializer();
$orderIds = $block->getOrderIds();
if (empty($orderIds)) {
    return '';
}
$ordersData = $viewModel->getMarketingData($orderIds);
if (empty($ordersData)) {
    return '';
}

$purchaseScript = "if (typeof _nzm !== 'undefined') {\n";
foreach ($ordersData as $order) {
    if (!(isset($order['products']) && !empty($order['products']))) {
        continue;
    }
    // To track an order, a user has to be identified.
    $purchaseScript .= '_nzm.identify(' . $serializer->serialize($order['buyer']) . ");\n";
    foreach ($order['products'] as $product) {
        $purchaseScript .= "_nzm.run('ec:addProduct', " . $serializer->serialize($product) . ");\n";
    }
    $purchaseScript .= "_nzm.run('ec:setAction', 'purchase', "
        . $serializer->serialize($order['order']) . ");\n";
}
$purchaseScript .= "_nzm.run('send', 'pageview');\n}";
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $purchaseScript, false) ?>
