<?php
/** @var $block \Dazoot\Newsman\Block\Adminhtml\System\Config\TestCredentials */
$buttonLabel = $block->getData('button_label');
$testUrl = $block->getData('test_url');
$htmlId = $block->getData('html_id');
?>
<div class="actions actions-validate newsman-test-credentials">
    <a id="<?= /* @noEscape */ $htmlId ?>_button"
       class="action-default scalable"
       href="<?= /* @noEscape */ $testUrl ?>">
        <span><?= $escaper->escapeHtml($buttonLabel) ?></span>
    </a>
</div>
