<?php

?>

<style>
    svg {
        width: 50px;
        display: block;
        margin: 20px auto 0;
    }
    .path {
        stroke-dasharray: 1000;
        stroke-dashoffset: 0;
    }
    .path.circle {
        -webkit-animation: dash 0.9s ease-in-out;
        animation: dash 0.9s ease-in-out;
    }
    .path.line {
        stroke-dashoffset: 1000;
        -webkit-animation: dash 0.9s 0.35s ease-in-out forwards;
        animation: dash 0.9s 0.35s ease-in-out forwards;
    }
    .path.check {
        stroke-dashoffset: -100;
        -webkit-animation: dash-check 0.9s 0.35s ease-in-out forwards;
        animation: dash-check 0.9s 0.35s ease-in-out forwards;
    }
    .modal-popup p {
        text-align: center;
        margin: 20px 0 60px;
        font-size: 1.25em;
    }
    .modal-popup p.success {
        color: #73AF55;
    }
    .modal-popup p.error {
        color: #D06079;
    }
    @-webkit-keyframes dash {
        0% {
            stroke-dashoffset: 1000;
        }
        100% {
            stroke-dashoffset: 0;
        }
    }
    @keyframes dash {
        0% {
            stroke-dashoffset: 1000;
        }
        100% {
            stroke-dashoffset: 0;
        }
    }
    @-webkit-keyframes dash-check {
        0% {
            stroke-dashoffset: -100;
        }
        100% {
            stroke-dashoffset: 900;
        }
    }
    @keyframes dash-check {
        0% {
            stroke-dashoffset: -100;
        }
        100% {
            stroke-dashoffset: 900;
        }
    }
    p.external-link{
        font-style: italic;
    }
    div.error-wrapper {
        max-height: 300px;
        overflow: scroll;
        margin-bottom: 40px;
    }
    div.error-wrapper p{
        text-align: left;
    }
    .modal-popup.confirm .modal-inner-wrap {
        width: 80rem;
    }
    .modal-popup.confirm .modal-inner-wrap .modal-content{
        padding-right: 0;
    }
</style>

<!--[if lte IE 9]>
<style>
    .path {stroke-dasharray: 0 !important;}
</style>
<![endif]-->

<?php ?>

<?php foreach ($block->verify() as $result) : ?>
    <?php if ($result['has_error'] === false) : ?>

        <p class="success">test!</p>
        <p><?php echo $result['msg'] ?></p>

    <?php else : ?>

        <p class="error">test!</p>
        <div class="error-wrapper">
            <p><?php echo $block->formatErrorMsg($result['msg']) ?> </p>
        </div>

    <?php endif; ?>
<?php endforeach; ?>
