<script>
	var tvc_UA_ID = <?php echo json_encode($block->getUaId()); ?>;
	var tvc_cur = <?php echo json_encode($block->getLocalCurrency());?>;
	var tvc_ver =  <?php echo json_encode($block->getMagentoVersion());?>;
	var tvc_ip = <?php
		//echo json_encode($block->checkIP_anonymization());
		echo 0;
		?>;
	var tvc_OptOut = <?php
		//echo json_encode($block->checkOptOut_Enabled());
		echo 0;
		?>;

	var endpoint = "https://retargeting.newsmanapp.com";

	var _nzm = _nzm || [];
	var _nzm_config = _nzm_config || [];
	_nzm_tracking_server = endpoint;
	(function () {
		_nzm_config["disable_datalayer"] = 1;
		var a, methods, i;
		a = function (f) {
			return function () {
				_nzm.push([f].concat(Array.prototype.slice.call(arguments, 0)));
			}
		};
		methods = ['identify', 'track', 'run'];
		for (i = 0; i < methods.length; i++) {
			_nzm[methods[i]] = a(methods[i])
		}
		;
		s = document.getElementsByTagName('script')[0];
		var script_dom = document.createElement('script');
		script_dom.async = true;
		script_dom.id = 'nzm-tracker';
		script_dom.setAttribute('data-site-id', tvc_UA_ID);
		script_dom.src = endpoint + '/js/retargeting/track.js';
		s.parentNode.insertBefore(script_dom, s);
	})();

	if (tvc_ip == 1) {
		_nzm.run('set', 'anonymizeIp', true);
	}

	_nzm.run('require', 'ec');

</script>
<?php

list($tvc_data, $get_action) = $block->getAction();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if ($customerSession->isLoggedIn())
{
	$usrData = array();
	$usrData["firstname"] = $customerSession->getCustomer()->getFirstname();
	$usrData["lastname"] = $customerSession->getCustomer()->getLastname();
	$usrData["email"] = $customerSession->getCustomer()->getEmail();

	$usrData = json_encode($usrData);

	echo "<script>
			require(
					['Dazoot_Newsmanmarketing/js/newsmanmarketing','jquery'],
						function(newsmanmarketing){
							var obj = new newsmanmarketing();
							obj.tvc_identify($usrData);
						}
			);
		</script>";
}

if ($get_action == 'catalog_product_view')
{
	echo "<script>
			var tvc_pp =" . $tvc_data . ";
			require(
					['Dazoot_Newsmanmarketing/js/newsmanmarketing','jquery'], 
						function(newsmanmarketing){
							var obj = new newsmanmarketing();
							obj.tvc_pro_detail(tvc_pp);
							obj.tvc_add_to_cart(tvc_pp);
						}
			);
		</script>";
}
if ($get_action == 'catalog_category_view')
{
	echo "<script>
			var tvc_pgc =" . $tvc_data . ";
			require(
					['Dazoot_Newsmanmarketing/js/newsmanmarketing','jquery'], 
						function(newsmanmarketing){
							var obj = new newsmanmarketing();
							obj.tvc_get_impression(tvc_pgc);
							obj.tvc_impr_click(tvc_pgc);
						}
			);
		</script>";
}
if ($get_action == 'checkout_cart_index')
{
	echo "<script>
        var tvc_remove =" . $tvc_data . ";
        require(
                ['Dazoot_Newsmanmarketing/js/newsmanmarketing','jquery'], 
                    function(newsmanmarketing){
                        var obj = new newsmanmarketing();
                        obj.add_product_checkout(tvc_remove);
                    }
        );
        </script>";
}
if ($get_action == 'checkout_onepage_success')
{
	echo "<script>
		var tvc_oo =" . $tvc_data . ";
		var t_keys = Object.keys(tvc_oo);
		var t_last = t_keys[tvc_oo.length-1];
		require(
				['Dazoot_Newsmanmarketing/js/newsmanmarketing','jquery'], 
					function(newsmanmarketing){
						var obj = new newsmanmarketing();
						obj.tvc_transaction_call(tvc_oo,tvc_oo[t_last]);
					}
		);
		</script>";
}

?>
