<?php /* @var $block \Dazoot\Newsman\Block\System\Config\Segments */ ?>
	<script>
		require([
			'jquery',
			'prototype',
		], function (jQuery) {

			param = {};

			for(i = 0; i < $groupsCount; i++)
			{
				tempSegmentLabel = i;
				tempSegmentValue = jQuery("#newsman_syncData_" + i + "segment").val();
				param[tempSegmentLabel] = tempSegmentValue;
			}

			function syncronizeSegments() {
				params = param;
				new Ajax.Request(<?php echo $block->getAjaxSyncUrl() ?>, {
					loaderArea: false,
					asynchronous: true,
					parameters: params,
					dataType: "json",
					onSuccess: function (response) {
						console.log(response);
						jQuery('#infoPanel').css('display', 'block');
						jQuery('#msgType').html("Synchronization of segments completed..");
					},
					onError: function () {
						jQuery('#infoPanel').css('display', 'block');
						jQuery('#msgType').html("Synchronization of segments failed..");
					}
				});
			}

			jQuery('#synchronizeSegments_button').click(function () {
				syncronizeSegments();
				jQuery('#infoPanel').css('display', 'block');
				jQuery('#msgType').html("Synchronization of segments started..");
				console.log("Sync started");
			});
			jQuery('#closeInfoPanel').click(function () {
				jQuery('#infoPanel').css('display', 'none');
			});
		});
	</script>

<?php echo $block->getButtonHtml() ?>